name: Foundry CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        solc: ["0.8.19", "0.8.20"]  # Test multiple Solidity versions

    name: Foundry Project CI
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Step 2: Install Foundry
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # Step 3: Cache build artifacts
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            cache
            out
          key: ${{ runner.os }}-forge-${{ hashFiles('**/foundry.toml') }}
          restore-keys: |
            ${{ runner.os }}-forge-

      # Step 4: Build the project
      - name: Build the project
        run: |
          forge --version
          forge build --sizes
        id: build

      # Step 5: Run tests with gas report
      - name: Run tests
        run: |
          forge test -vvv --gas-report
        id: test

      # Step 6: Run coverage
      - name: Run coverage
        run: |
          forge coverage --report lcov
        id: coverage

      # Step 7: Upload coverage report
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: lcov.info