name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        solc: ["0.8.19", "0.8.20"]  # Test multiple Solidity versions

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            cache
            out
          key: ${{ runner.os }}-forge-${{ hashFiles('**/foundry.toml') }}
          restore-keys: |
            ${{ runner.os }}-forge-

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv --gas-report
        id: test

      - name: Run Coverage
        run: |
          forge coverage --report lcov
        id: coverage