name: Foundry CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        solc: ["0.8.19", "0.8.20"] # Test multiple Solidity versions
    name: Foundry Project CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Build contracts
        run: forge build

      - name: Run tests
        run: forge test --match-path test/**/*

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: build-artifacts
          path: out/
