name: Foundry project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: latest

      - name: Install dependencies
        run: forge install

      - name: Check formatting
        run: forge fmt --check

      - name: Only build Raffle.sol (exclude mocks in lib)
        run: forge build --contracts src/Raffle.sol

      - name: Run tests
        run: forge test -vvv
